import { writeFileSync } from 'fs';

// Source: PublicaMundi MappingAPI US states GeoJSON (public sample data).
const SOURCE = 'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json';
const res = await fetch(SOURCE);
const geo = await res.json();

// Drop non-continental territories so the silhouette stays clean.
const EXCLUDE = new Set(['Alaska', 'Hawaii', 'Puerto Rico']);

// Projection bounds (continental US).
const LNG_MIN = -125;
const LNG_MAX = -66.5;
const LAT_MIN = 24;
const LAT_MAX = 49.5;
const MID_LAT = (LAT_MIN + LAT_MAX) / 2;
const COS = Math.cos((MID_LAT * Math.PI) / 180); // aspect correction for x

const HEIGHT = 560;
const ky = HEIGHT / (LAT_MAX - LAT_MIN);
const kx = ky * COS;
const WIDTH = (LNG_MAX - LNG_MIN) * kx;

function project(lng, lat) {
  const x = (lng - LNG_MIN) * kx;
  const y = (LAT_MAX - lat) * ky;
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
}

function ringToPath(ring) {
  let d = '';
  for (let i = 0; i < ring.length; i++) {
    const [lng, lat] = ring[i];
    if (lng < LNG_MIN - 5 || lng > LNG_MAX + 5) continue; // skip far outliers
    const [x, y] = project(lng, lat);
    d += (i === 0 ? 'M' : 'L') + x + ' ' + y;
  }
  return d + 'Z';
}

const states = [];
for (const f of geo.features) {
  const name = f.properties.name;
  if (EXCLUDE.has(name)) continue;
  const g = f.geometry;
  let polys = [];
  if (g.type === 'Polygon') polys = [g.coordinates];
  else if (g.type === 'MultiPolygon') polys = g.coordinates;
  let d = '';
  for (const poly of polys) {
    for (const ring of poly) {
      if (ring.length < 4) continue;
      d += ringToPath(ring);
    }
  }
  if (d) states.push({ name, d });
}

const cities = {
  greensboro: project(-79.792, 36.0726),
  cambridge: project(-71.1097, 42.3736),
  collegePark: project(-76.9378, 38.9897),
  newHaven: project(-72.9279, 41.3083),
};

const out = `// AUTO-GENERATED by gen-map.mjs — continental US state outlines (equirectangular, aspect-corrected).
// Do not edit by hand; regenerate if the projection changes.

export const MAP_VIEWBOX = '0 0 ${Math.round(WIDTH)} ${HEIGHT}';

export const US_STATE_PATHS: { name: string; d: string }[] = ${JSON.stringify(states)};

export const CITY_XY = {
  greensboro: { x: ${cities.greensboro[0]}, y: ${cities.greensboro[1]} },
  cambridge: { x: ${cities.cambridge[0]}, y: ${cities.cambridge[1]} },
  collegePark: { x: ${cities.collegePark[0]}, y: ${cities.collegePark[1]} },
  newHaven: { x: ${cities.newHaven[0]}, y: ${cities.newHaven[1]} },
} as const;
`;

writeFileSync('./components/usaMapData.ts', out);
console.log('viewBox 0 0', Math.round(WIDTH), HEIGHT);
console.log('states', states.length);
console.log('cities', cities);
const bytes = Buffer.byteLength(out, 'utf-8');
console.log('output KB', (bytes / 1024).toFixed(1));
